name: Coverity Scan
on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - name: Download coverity scan build tool
      run: |
        curl -o cov-analysis-linux64.tar.gz https://scan.coverity.com/download/cxx/linux64 \
          --form project=$GITHUB_REPOSITORY \
          --form token=$TOKEN
        mkdir cov-analysis-linux64
        tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

    - name: configure
      run: ./configure

    - name: Build with cov-build
      run: |
        export PATH=$(pwd)/cov-analysis-linux64/bin:$PATH
        cov-build --dir cov-int make

    - name: Submit result to coverity scan
      run: |
        tar czvf result.tgz cov-int
        curl \
          --form project=$GITHUB_REPOSITORY \
          --form token=$TOKEN \
          --form email=bugs@ircd-hybrid.org \
          --form file=@result.tgz \
          --form version=$(git rev-parse HEAD) \
          --form description=$(date +%Y-%m-%dT%H:%M:%S%z) https://scan.coverity.com/builds?project=$GITHUB_REPOSITORY
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
